Document: kconfig-frontends
Title: Debian kconfig-frontends Manual
Author: <insert document author here>
Abstract: This manual describes what kconfig-frontends is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kconfig-frontends/kconfig-frontends.sgml.gz

Format: postscript
Files: /usr/share/doc/kconfig-frontends/kconfig-frontends.ps.gz

Format: text
Files: /usr/share/doc/kconfig-frontends/kconfig-frontends.text.gz

Format: HTML
Index: /usr/share/doc/kconfig-frontends/html/index.html
Files: /usr/share/doc/kconfig-frontends/html/*.html
